Address linter issues and enable github actions for it
tendermint/spn pull request #136
Opened 2021-05-03 06:24 UTC by dshulyak

Changes are straightforward and only addressing reported issues.
I disabled `interfacer` linter, as it doesn't always report relevant things,
also disabled rule G404: weak randomness linter, it recommends using crypto.Rand
even when it is unnecessary.

2021-05-03 08:51 UTC, dshulyak commented
@fadeev @lubtd who can add me to tendermint org or at least enable CI for this PR?

2021-05-03 08:54 UTC, fadeev commented
@dshulyak I'll be adding you to both repos now!

2021-05-03 08:55 UTC, ilgooz commented
@dshulyak for the time being, I triggered the checks for this PR manually. (your following commits should also work since you're now authorized with this one)

2021-05-03 09:06 UTC, ilgooz requested changes
Congrats on the first PR!!!! 🎊 🍪

2021-05-03 09:06 UTC, ilgooz commented on internal/utils/parse_test.go
> +			err:         "strconv.ParseInt: parsing \"%s\": value out of range",
Instad of comparing strings, can we unwrap the received error and compare with defined error values.
e.g.: https://golang.org/pkg/strconv/#pkg-variables

2021-05-03 09:20 UTC, dshulyak commented on internal/utils/parse.go
> +package utils
i don't think that it is meant to be reusable outside of spn

2021-05-04 11:22 UTC, dshulyak commented
@ilgooz do you want me to fix more things?

2021-05-04 12:01 UTC, ilgooz approved these changes
It is very good, thank's for changes.

2021-05-04 14:21 UTC, lubtd approved these changes
Thanks, it's a great PR

2021-05-04 14:29 UTC, merged