feat(launch): filter genesis and vested accounts by chain ID flag
tendermint/spn pull request #224
Opened 2021-08-03 22:08 UTC by Pantani

Closes #178

### What does this PR does?

Create a `chain-id` flag to filter `all` requests for genesis and vested accounts

2021-08-04 12:34 UTC, lubtd commented
I'm personally advocating for having `chainID` as a positional argument and removing the ability to query all requests from all chains. I don't think there is a practical use case of this.

2021-08-04 12:38 UTC, lubtd requested changes

2021-08-04 12:38 UTC, lubtd commented on x/launch/keeper/grpc_query_genesis_account.go
> +		if req.ChainID == "" || genesisAccount.ChainID == req.ChainID {
For performance reason we should use `query.Paginate` with the longest common prefix. So in this case the prefix that include the `chainID`

For this we can add a method that returns the prefix with `chainID` in `types/key_[accounttype].go` then we provide this prefix to the `prefix.NewStore` method above

2021-08-05 08:42 UTC, lubtd commented on proto/launch/query.proto
> +	string chainID = 1;
We don't need the `chainID` in the response

2021-08-05 08:42 UTC, lubtd commented on x/launch/client/cli/query_genesis_account_test.go
> +			sample.GenesisAccount("foo", strconv.Itoa(i)),
We should test with a valid `chainID` from `sample`

2021-08-05 16:46 UTC, lubtd reviewed
Just a single fix and that's it

2021-08-05 16:46 UTC, lubtd commented on x/launch/client/cli/query_vested_account.go
> +		Short: "list all vestedAccount [chainID]",
```suggestion
		Short: "list all vestedAccount",
```

2021-08-05 16:46 UTC, lubtd commented on x/launch/client/cli/query_vested_account.go
>  		Use:   "list-vested-account",
```suggestion
		Use:   "list-vested-account [chainID]",
```

2021-08-05 16:47 UTC, lubtd commented
The attached issue https://github.com/tendermint/spn/issues/178 also include list validators by `chainID` so we will have to handle this to close the issue. This can be completed in a separate PR

2021-08-05 17:35 UTC, Pantani commented
> The attached issue #178 also include list validators by `chainID` so we will have to handle this to close the issue. This can be completed in a separate PR

we can do it in the same PR we will create the request to add the validator

2021-08-06 08:27 UTC, lubtd commented
> we can do it in the same PR we will create the request to add the validator

Mmh so do you plan to do it on this PR?

Because you requested for a review but the validator query still doesn't include `chainID`

2021-08-06 15:29 UTC, Pantani commented
> > we can do it in the same PR we will create the request to add the validator
> 
> Mmh so do you plan to do it on this PR?
> 
> Because you requested for a review but the validator query still doesn't include `chainID`

Done!! 
I made a mistake. I was thought we need to implement #161 before it. Forget my last comment

2021-08-06 15:36 UTC, lubtd commented
> > > we can do it in the same PR we will create the request to add the validator
> > 
> > 
> > Mmh so do you plan to do it on this PR?
> > Because you requested for a review but the validator query still doesn't include `chainID`
> 
> Done!!
> I made a mistake. I was thought we need to implement #161 before it. Forget my last comment

Nope

Well we will need `MsgSettleRequest` in order to test the queries from the CLI but this is not a very big concern as long as we have all the tests

2021-08-06 16:35 UTC, lubtd approved these changes
👍

2021-08-09 10:16 UTC, ilgooz approved these changes

2021-08-09 12:10 UTC, merged