test: improve coverage
tendermint/spn pull request #280
Opened 2021-08-30 10:01 UTC by lubtd

Improve coverage of the different tests

- Test untested methods
- Add new test cases
- Fix trigger launch and revert launch messages tests
- Assert errors for `keeper/msg_...` tests

2021-08-30 10:02 UTC, lubtd commented
@Pantani I fixed what I observed. I let you add other improvements in this PR if you spot few

2021-08-30 15:51 UTC, Pantani requested changes

2021-08-30 15:51 UTC, Pantani commented on x/profile/keeper/coordinator_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/tendermint/spn/testutil/sample"
```

2021-08-30 15:51 UTC, Pantani commented on x/profile/keeper/coordinator_by_address_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"fmt"
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/tendermint/spn/testutil/sample"
```

2021-08-30 15:51 UTC, Pantani commented on x/launch/keeper/msg_server_trigger_launch_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	profiletypes "github.com/tendermint/spn/x/profile/types"
```

2021-08-30 15:51 UTC, Pantani commented on x/launch/keeper/msg_server_revert_launch_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	profiletypes "github.com/tendermint/spn/x/profile/types"
```

2021-08-30 15:51 UTC, Pantani commented on x/launch/keeper/msg_server_create_chain_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	profiletypes "github.com/tendermint/spn/x/profile/types"
```

2021-08-30 15:51 UTC, Pantani commented on x/launch/keeper/grpc_query_params_test.go
> +	"github.com/tendermint/spn/x/launch/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/stretchr/testify/require"
	testkeeper "github.com/tendermint/spn/testutil/keeper"
	"github.com/tendermint/spn/testutil/sample"
	"github.com/tendermint/spn/x/launch/types"
```

2021-08-30 20:16 UTC, Pantani commented on x/launch/keeper/msg_server_edit_chain_test.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
	"testing"

	sdk "github.com/cosmos/cosmos-sdk/types"
	profiletypes "github.com/tendermint/spn/x/profile/types"
```

2021-08-31 06:11 UTC, ilgooz submitted a review, later dismissed

2021-08-31 15:13 UTC, ilgooz submitted a review, later dismissed

2021-09-01 03:28 UTC, Pantani approved these changes

2021-09-01 03:28 UTC, Pantani approved these changes

2021-09-01 12:33 UTC, merged