feat(campaign): initialize mainnet vesting account
tendermint/spn pull request #296
Opened 2021-09-08 14:05 UTC by lubtd

Initialize the map for mainnet vesting accounts

Unlike `VestingAccount` from `launch`, the `MainnetVestingAccount` has `ShareVestingOptions` where the vesting options contain shares instead of coins.

The final vesting option with real coins is interpreted when the chain is launched

2021-09-08 15:27 UTC, Pantani requested changes

2021-09-08 15:27 UTC, Pantani commented on proto/campaign/query.proto
> +
```suggestion
  uint64 campaignID = 1;
  string address = 2;
```

2021-09-08 15:27 UTC, Pantani commented on x/campaign/client/cli/query_mainnet_vesting_account_test.go
> +	"github.com/tendermint/spn/x/campaign/types"
```suggestion
	"fmt"
	"strconv"
	"testing"

	"github.com/cosmos/cosmos-sdk/client/flags"
	clitestutil "github.com/cosmos/cosmos-sdk/testutil/cli"
	"github.com/stretchr/testify/require"
	tmcli "github.com/tendermint/tendermint/libs/cli"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/tendermint/spn/testutil/network"
	"github.com/tendermint/spn/testutil/sample"	
	"github.com/tendermint/spn/x/campaign/client/cli"
	"github.com/tendermint/spn/x/campaign/types"
```

2021-09-08 15:27 UTC, Pantani commented on x/campaign/keeper/mainnet_vesting_account.go
> +
```suggestion
```

2021-09-08 15:27 UTC, Pantani commented on x/campaign/keeper/mainnet_vesting_account.go
> +	))
```suggestion
	b := store.Get(types.MainnetVestingAccountKey(campaignID, address))
```

2021-09-08 15:27 UTC, Pantani commented on x/campaign/keeper/mainnet_vesting_account.go
> +	))
```suggestion
	store.Delete(types.MainnetVestingAccountKey(campaignID, address))
```

2021-09-08 15:27 UTC, Pantani commented on x/campaign/keeper/mainnet_vesting_account_test.go
> +
```suggestion
```

2021-09-08 18:49 UTC, Pantani commented on x/campaign/client/cli/query_mainnet_vesting_account_test.go
> +	}
```suggestion
		state.MainnetVestingAccountList = append(state.MainnetVestingAccountList, sample.MainnetVestingAccount(
			uint64(i),
			sample.AccAddress(),
			sample.Shares(),
			sample.ShareVestingOptions(),
		))
	}
```

2021-09-09 16:18 UTC, Pantani approved these changes

2021-09-10 09:04 UTC, ilgooz approved these changes

2021-09-10 13:35 UTC, Pantani approved these changes

2021-09-10 13:47 UTC, merged