feat(launch): support proxied peers for genesis validator
tendermint/spn pull request #441
Opened 2022-01-06 01:49 UTC by Pantani

Closes #407

### What does this PR does?

### How to test?

2022-01-07 10:42 UTC, lubtd requested changes

2022-01-07 10:42 UTC, lubtd commented on proto/launch/genesis_validator.proto
> +  Peer peer = 6;
Can we use `[(gogoproto.nullable) = false]` to not have a pointer here

2022-01-07 10:42 UTC, lubtd commented on testutil/sample/launch.go
> +func GenesisValidatorPeer() *launch.Peer {
I think we can return a plain value instead of pointer from comment above

2022-01-07 10:42 UTC, lubtd commented on x/launch/client/cli/tx_request_add_validator.go
> +				}
I would suggest creating methods in `types/peer.go` to instanciate each type of peer like for other `oneof`

2022-01-07 10:42 UTC, lubtd commented on x/launch/types/message_request_add_validator.go
> +	peer *Peer,
```suggestion
	peer Peer,
```

2022-01-07 10:42 UTC, lubtd commented on x/launch/types/message_request_add_validator.go
> +		}
We should implement a Peer.Validate()

2022-01-11 16:28 UTC, lubtd reviewed
👍

There is an issue with the cli apparently

```
spnd tx profile create-coordinator --from alice
spnd tx launch create-chain toast-0 test.com 0xaaa --from alice
echo "haha" > gentx.json
spnd tx launch request-add-validator 1 gentx.json 0xa 1atom foo.com --from alice

Error: invalid peer: invalid peer connection: the peer is invalid
```
This seems to be the error when the peer is not recognised (among the `oneof`)

2022-01-11 16:28 UTC, lubtd commented on x/launch/types/message_request_add_validator.go
> +		return sdkerrors.Wrap(err, "invalid peer")
```suggestion
		return sdkerrors.Wrap(ErrInvalidPeer, err.Error())
```

2022-01-11 16:28 UTC, lubtd commented on x/launch/types/peer.go
> +		return sdkerrors.Wrap(ErrInvalidPeer, "invalid peer connection")
The wrap should be performed in the upper lever method
I think we can return simple `errors.New`

2022-01-11 16:28 UTC, lubtd commented on x/launch/types/peer.go
> +func (m Peer) Validate() error {
We can also check that `Peer.Id` is non-nil

2022-01-11 16:28 UTC, lubtd commented on x/launch/types/request_content.go
> +		return sdkerrors.Wrap(ErrInvalidPeer, "invalid peer connection")
I think you forgot `Peer.Validate()` here 🙂

2022-01-12 06:42 UTC, ilgooz approved these changes

2022-01-12 07:34 UTC, lubtd approved these changes
👍

2022-01-12 07:35 UTC, merged