feat(profile): Implement `MsgSetValidatorConsAddress` message
tendermint/spn pull request #453
Opened 2022-01-18 01:14 UTC by Pantani

Closes #430

### What does this PR does?

Implement `MsgSetValidatorConsAddress` message

### How to test?

2022-01-24 16:16 UTC, barriebyron reviewed
I love grammar, so always look for how every word is exposed to our users 

nits and editorial suggestions :)

2022-01-27 14:04 UTC, lubtd requested changes
An optimization we can have is to add the `nonce` and `chainID` in the `MsgSetValidatorConsAddress ` message. So that we can use `CreateSignMessage` to generate the signMessage in `ValidateMessage` and  verify the signature as a static check

Then, in the message handler we simply check if the nonce used is the current nonce for the consKey and the chainID is `ctx.ChainID()` 

WDYT?

2022-01-27 17:48 UTC, Pantani commented
> An optimization we can have is to add the `nonce` and `chainID` in the `MsgSetValidatorConsAddress ` message. So that we can use `CreateSignMessage` to generate the signMessage in `ValidateMessage` and verify the signature as a static check
> 
> Then, in the message handler we simply check if the nonce used is the current nonce for the consKey and the chainID is `ctx.ChainID()`
> 
> WDYT?

Sure!! added. This new implementation also supports different type of keys

2022-01-27 20:44 UTC, lubtd commented on proto/profile/tx.proto
> +  bytes validatorPubKey = 2;
```suggestion
  bytes validatorConsPubKey = 2;
```

We should precise this is the consensus key which is different from the validator SDK address

2022-01-27 20:44 UTC, lubtd commented on x/profile/client/cli/tx_set_validator_cons_address.go
> +		Short: "Associate a consensus address for a specific SPN address",
```suggestion
		Short: "Associate a Tendermint consensus address to a specific validator address on SPN",
```

2022-01-28 08:31 UTC, lubtd commented
> > An optimization we can have is to add the `nonce` and `chainID` in the `MsgSetValidatorConsAddress ` message. So that we can use `CreateSignMessage` to generate the signMessage in `ValidateMessage` and verify the signature as a static check
> > Then, in the message handler we simply check if the nonce used is the current nonce for the consKey and the chainID is `ctx.ChainID()`
> > WDYT?
> 
> Sure!! added. This new implementation also supports different type of keys

I meant doing the signature verification
```
if !valPubKey.VerifySignature(currentNonce, ctx.ChainID(), msg.Signature) {
return &types.MsgSetValidatorConsAddressResponse{},
	sdkerrors.Wrapf(types.ErrInvalidValidatorSignature,
		"invalid signature for consensus address: %s - %s",
		consAddress,
		msg.Signature,
	)
}
```
in the `Validate` of `types/message_set_validator_cons_address.go` instead of having it in `keeper/msg_server_set_validator_cons_address.go` since it's a static check once we have the nonce and the chain ID. So we would add the nonce and the chain ID in the message `MsgSetValidatorConsAddress ` (not the message to sign)

and then we check only the nonce and chain-id in `keeper/msg_server_set_validator_cons_address.go`

2022-01-28 08:32 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +	validatorByConsAddr, found := k.GetValidatorByConsAddress(ctx, consAddress)
I think we should allow the validator to set a new validator address for the consensus key since the signature prove they are the owner of it

2022-01-28 08:32 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +	validatorStore, found := k.GetValidator(ctx, validatorByConsAddr.ValidatorAddress)
```suggestion
	validatorStore, found := k.GetValidator(ctx, msg.ValidatorAddress)
```
Isn't a mistake here?

2022-01-28 08:32 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +	k.SetValidatorByConsAddress(ctx, types.ValidatorByConsAddress{
We should also reset `ValidatorByConsAddress` if there is an existing consensus address associated to the address

2022-01-28 14:16 UTC, Pantani commented
@lubtd sorry, I understand the suggestion now. I prefer the user pass only the key, and we can get the chain id and the nonce automatically in the keeper, so the user doesn't need to query the `chainID` and `nonce`, which is more user-friendly. And we can add the nonce and the chain-id as an optional parameter for the CLI.

2022-01-28 14:42 UTC, lubtd commented
> so the user doesn't need to query the chainID and nonce

Mmh, the user would need to query the nonce at some point to generate the signature anyway?
This is an internal change mostly so we could maybe discuss it in the next SPN call

2022-01-28 14:44 UTC, Pantani commented
@lubtd, I will apply your suggestion, and we can discuss the improvement later in the call. If we make the signature validation into the `ValidateBasic` method, we should remove the `signature` CLI flag because the logic will be hard to handle

2022-01-28 14:48 UTC, lubtd commented
Sorry, I didn't precise in my latest message, I wanted to say that we could go the current way for this PR and discuss the eventual change in the next call

> we should remove the signature CLI flag because the logic will be hard to handle

In this case the `nonce` would become a required argument. The flag `--signature` could still be used, the signature would not be generated in the CLI method

2022-01-28 15:36 UTC, Pantani commented
But don't have too much sense to have the signature flag if we need to always pass the nonce to validate into the `ValidateBasic` method, the sign will be always the same

2022-01-28 15:43 UTC, lubtd commented
> But don't have too much sense to have the signature flag if we need to always pass the nonce to validate into the `ValidateBasic` method, the sign will be always the same

I believe in fact, `--signature` should be an option that allows to not provide the full validator key file (that contain the private key) but only the public key since the signature has been generated externally

Maybe we can ship this PR without `--signature` and see later the advanced interface with signature manually generated

2022-01-28 18:50 UTC, lubtd reviewed
👍

2022-01-28 18:50 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +	// get the current validator to eventually overwrite description
```suggestion
	// get the current validator to eventually overwrite description and remove existing consensus key
```

2022-01-28 18:50 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +			sdkerrors.Wrap(types.ErrInvalidValidatorKey, string(msg.ValidatorConsPubKey))
I think it can be a critical error since this check is performed in `Validate` message

2022-01-28 19:03 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +		ValidatorAddress: valPubKey.Address().String(),
```suggestion
		ValidatorAddress: msg.ValidatorAddress,
```

2022-01-28 19:03 UTC, lubtd commented on x/profile/keeper/msg_server_set_validator_cons_address.go
> +		Address:          valPubKey.Address().String(),
```suggestion
		Address:         msg.ValidatorAddress,
```

2022-01-30 15:12 UTC, lubtd reviewed
Great👍

Just one last comment
When registering the consensus key with another address, the previous validator keep the consensus address in its profile:
```
spnd tx profile set-validator-cons-address priv_validator_key.json 0 --from alice
spnd tx profile set-validator-cons-address priv_validator_key.json 1 --from bob

spnd q profile list-validator
validator:
- address: spn1deu7lhyx7aexggv6a4keqycvukzlelkcj2w55h
  consensusAddress: spnvalcons1twduj8s52ccsscu47e0s2asawd58sln4cpfp4e
- address: spn1t6mrjcm5elren67zpqtqesmhed9ujk4cf9hz47
  consensusAddress: spnvalcons1twduj8s52ccsscu47e0s2asawd58sln4cpfp4e
```

we should in the message check if the consensus key is currently registered with `k.GetValidatorByConsAddress` and eventually remove the cons address of the previous validator

2022-01-31 17:21 UTC, Pantani commented
> Great👍
> 
> Just one last comment When registering the consensus key with another address, the previous validator keep the consensus address in its profile:
> 
> ```
> spnd tx profile set-validator-cons-address priv_validator_key.json 0 --from alice
> spnd tx profile set-validator-cons-address priv_validator_key.json 1 --from bob
> 
> spnd q profile list-validator
> validator:
> - address: spn1deu7lhyx7aexggv6a4keqycvukzlelkcj2w55h
>   consensusAddress: spnvalcons1twduj8s52ccsscu47e0s2asawd58sln4cpfp4e
> - address: spn1t6mrjcm5elren67zpqtqesmhed9ujk4cf9hz47
>   consensusAddress: spnvalcons1twduj8s52ccsscu47e0s2asawd58sln4cpfp4e
> ```
> 
> we should in the message check if the consensus key is currently registered with `k.GetValidatorByConsAddress` and eventually remove the cons address of the previous validator

nice catch. I added the logic to remove the old consensus key

2022-01-31 20:02 UTC, lubtd approved these changes
👍

2022-01-31 20:03 UTC, merged