feat(`monitoringc`): add verification of client for IBC handshake
tendermint/spn pull request #456
Opened 2022-01-20 10:45 UTC by lubtd

Scaffold map `ProviderClientID` to register the official client ID of a provider chain from the launch ID once the IBC connection is established
Scaffold map `LaunchIDFromVerifiedClientID` to retrieve the associated launch ID for a verified client and check if a client is verified
Implement handshake verification in `module_ibc.go`

TODO

- [ ] mocking capability for IBC modules
- [ ] test for `handshake.go`

2022-01-22 12:59 UTC, Pantani requested changes

2022-01-22 12:59 UTC, Pantani commented on proto/monitoringc/provider_client_id.proto
> +
```suggestion
```

2022-01-22 12:59 UTC, Pantani commented on x/monitoringc/client/cli/query_launch_id_from_verified_client_id.go
> +		Short: "list all LaunchIDFromVerifiedClientID",
```suggestion
		Short: "list all LaunchIDFromVerifiedClientID",
		Args:  cobra.NoArgs,
```

2022-01-22 12:59 UTC, Pantani commented on x/monitoringc/module.go
> +	"context"
```suggestion
	"context"
	"encoding/json"
	"fmt"

```

2022-01-22 16:34 UTC, lubtd commented on x/monitoringc/client/cli/query.go
> +	cmd.AddCommand(CmdShowLaunchIDFromVerifiedClientID())
Params as last

2022-01-25 03:42 UTC, Pantani approved these changes

2022-01-25 03:42 UTC, Pantani commented on x/monitoringc/module.go
> +	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
```suggestion
	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx)) // nolint
```

2022-01-25 12:36 UTC, merged