feat: launch events
tendermint/spn pull request #517
Opened 2022-02-11 21:19 UTC by aljo242

Closes #427

### What does this PR does?

Add `events.proto` for the `x/launch` module and emit cosmos sdk typed events on key updates.  The events should contain all information necessary for a client or DB to get the state of the chain without running any queries.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [X] Respect code style and lint
- [ ] Update documentation (*.md) (if needed)

2022-02-14 15:05 UTC, lubtd commented
As discussed, let's keep this feature on hold

2022-02-14 15:33 UTC, aljo242 commented
> As discussed, let's keep this feature on hold

should we close the PR or keep open?

2022-02-14 16:14 UTC, lubtd commented
> should we close the PR or keep open?

Let's just keep it here for now

2022-02-14 17:57 UTC, Pantani commented on x/launch/keeper/msg_server_create_chain.go
> +	chain, found := k.GetChain(ctx, id)
I think we don't need to check if the chain exists.

2022-02-14 17:57 UTC, Pantani commented on x/launch/keeper/msg_server_request_add_account.go
> +	var err error
```suggestion
	var (
		requestID uint64
		err error
	)
```

2022-02-14 17:57 UTC, Pantani commented on x/launch/keeper/msg_server_request_remove_account.go
> +	var err error
```suggestion
	var (
		requestID uint64
		err error
	)
```

2022-04-20 14:23 UTC, lubtd commented
Hey @aljo242, we can move forward with this task :) 
Normally the conflicts should be quite generic

2022-04-22 13:45 UTC, giunatale requested changes

2022-04-22 13:45 UTC, giunatale commented on x/launch/keeper/msg_edit_chain.go
> +	err = ctx.EventManager().EmitTypedEvent(&types.EventChainUpdated{
lint: ineffectual assignment to err (ineffassign)

2022-04-22 13:45 UTC, giunatale commented on x/launch/keeper/msg_revert_launch.go
> +	err = ctx.EventManager().EmitTypedEvent(&types.EventLaunchReverted{
ineffectual assignment to err (ineffassign)

2022-04-25 13:33 UTC, aljo242 commented
CodeCov again :|

2022-04-26 10:33 UTC, Matthews3301 commented on x/launch/keeper/msg_request_add_validator.go
> +			CampaignID:       chain.CampaignID,
Would it be possible to also emit:
1. New validator operator address.
2. The address of the account which approved this validator (coordinator)

2022-04-26 14:53 UTC, aljo242 commented
@Matthews3301 I have added the `CoordinatorAddress` to the Event.  The validator operator address can be accessed with the `GenesisValidator` field of the event, which is already present.

2022-04-26 14:56 UTC, Matthews3301 commented
> @Matthews3301 I have added the `CoordinatorAddress` to the Event. The validator operator address can be accessed with the `GenesisValidator` field of the event, which is already present.

Thank you - looks good. Maybe for consistency sake, we should have the same data emitted for `EventValidatorRemoved`?

2022-04-26 14:59 UTC, aljo242 commented
> > @Matthews3301 I have added the `CoordinatorAddress` to the Event. The validator operator address can be accessed with the `GenesisValidator` field of the event, which is already present.
> 
> Thank you - looks good. Maybe for consistency sake, we should have the same data emitted for `EventValidatorRemoved`?

The only information that could possibly change between "adding" and "removing" is the `CoordinatorAddress`, so I will add that.  Do we need that information for any of the other events?

2022-04-26 15:44 UTC, Matthews3301 commented
@aljo242 None that I'm aware of. This should be good for now.

2022-04-26 20:06 UTC, lubtd commented on x/launch/keeper/msg_create_chain.go
> +	err = ctx.EventManager().EmitTypedEvent(&types.EventChainCreated{
In `campaign`, a chain for the mainnet is also created by calling `CreateNewChain` when sending `MsgIninitializeMainnet`

Maybe we could have this event in `CreateNewChain` to catch everything? Or we can eventually consider a `MainnetInitialized` event

2022-04-26 20:06 UTC, lubtd commented on x/launch/keeper/request.go
> +		err = ctx.EventManager().EmitTypedEvent(&types.EventGenesisAccountAdded{
For all events here, we also emit the event in the message for request when sent by the coordinator. So the event would be sent twice

We should keep only these events here

2022-04-26 20:53 UTC, aljo242 commented
@lubtd I moved the event emission to `CreateNewChain`

2022-04-27 11:55 UTC, lubtd reviewed
Tested with the CLI👍

2022-04-27 11:55 UTC, lubtd commented on x/launch/keeper/request.go
> +			CoordinatorAddress: coord.Address,
I think we can have `CoordinatorAddress` for every request applied event for consistency

2022-04-27 14:10 UTC, lubtd approved these changes

2022-04-27 14:16 UTC, giunatale approved these changes

2022-04-27 14:33 UTC, merged