feat(`profile`): add check and test
tendermint/spn pull request #551
Opened 2022-02-21 20:13 UTC by aljo242

Closes #547

2022-02-21 20:55 UTC, lubtd requested changes

2022-02-21 20:55 UTC, lubtd commented on x/profile/types/genesis.go
> +		if !elem.Active {
In the previous state, there was a 1-1 relationship between `Coordinator` and `CoordinatorByAddress` therefore we checked that all `Coordinator` had an associated `CoordinatorByAddress`

Now a `Coordinator` can eventually have no matched `CoordinatorByAddress` but if this is the case  the coordinator must be inactive.

Therefore we should rather have condition that allows inactive coordinators in the initial genesis

```
if !found && elem.Active {
	return errors.New("....")
}

if found && !elem.Active {
	return errors.New("....")
}
```

2022-02-21 21:49 UTC, Pantani approved these changes

2022-02-22 06:54 UTC, lubtd approved these changes
👍

One comment: we should try to put PR name as explicit as possible

2022-02-22 06:54 UTC, merged