fix(`launch`): add check for MsgSettleRequest sim
tendermint/spn pull request #562
Opened 2022-02-23 17:53 UTC by aljo242

Closes #405

Perform a check using the logic of `ApplyRequest()` without modifying state.  Implemented in a new function in the simulation package called `checkRequest()`.

2022-02-23 17:55 UTC, giunatale commented
Is this fixing the current simulation error on `develop`?

2022-02-23 17:57 UTC, aljo242 commented
> Is this fixing the current simulation error on `develop`?

Yessir :)

2022-02-23 18:01 UTC, giunatale requested changes
small lint fix, otherwise LGTM

2022-02-23 18:04 UTC, giunatale commented on x/launch/simulation/store.go
> +	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
we should keep this format here, where imports are grouped with spn at the bottom. That's what I've seen done everywhere.

2022-02-23 18:06 UTC, lubtd commented
Can you try the simulation with some different seed to ensure if we no longer get this error?

```
starport chain simulate --seed [nb]
```

2022-02-23 18:07 UTC, aljo242 commented
> 

Ran with seeds [1, 15] and everything is ok.

2022-02-23 18:21 UTC, aljo242 commented on x/launch/simulation/store.go
> +func checkRequest(
Ok, I removed the check part and created `CheckRequest` in the keeper package. This means we perform the switch-case on the request contents twice (once to check, once to apply), but the code is a bit cleaner now i think.

2022-02-23 18:24 UTC, aljo242 commented
Ok, I removed the check part and created CheckRequest in the keeper package. This means we perform the switch-case on the request contents twice (once to check, once to apply), but the code is a bit cleaner now i think.

2022-02-23 18:31 UTC, lubtd commented
> Ok, I removed the check part and created CheckRequest() in the keeper package. This means we perform the switch-case on the request contents twice (once to check, once to apply), but the code is a bit cleaner now i think.

This is fine

2022-02-23 20:06 UTC, lubtd commented on x/launch/keeper/request.go
> +func CheckRequest(
We should create the `TestCheckRequest` test to test request checking

`TestApplyRequest` would keep the state transition assertion and should verify that it fails if a request is invalid (without testing all invalid requests)

2022-02-24 09:56 UTC, giunatale submitted a review, later dismissed

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 10:08 UTC, lubtd commented on x/launch/keeper/request_test.go
> +			err:     nil,
```suggestion
```

2022-02-24 15:24 UTC, lubtd approved these changes

2022-02-24 15:25 UTC, merged