refactor: remove uint64 to int64 conversions
tendermint/spn pull request #593
Opened 2022-03-03 15:36 UTC by aljo242

Closes #580

### What does this PR does?

Removes the `uint64` -> `int64` conversions that I could find in our codebase.  Also changes all `BlockHeight` variables to `int64`.  This was the source of some of the conversions and makes sense because the Cosmos SDK itself stores blockheight as int64.

2022-03-03 20:40 UTC, Pantani submitted a review, later dismissed
LGMT

2022-03-03 21:01 UTC, lubtd requested changes

2022-03-03 21:01 UTC, lubtd commented on proto/reward/reward_pool.proto
> +  int64 currentRewardHeight = 6;
We have a `Validate` method in `RewardPool`, we should check the values are non-negative

2022-03-03 22:34 UTC, giunatale requested changes
agreed with @lubtd on the non-negativity checks

2022-03-03 22:34 UTC, giunatale commented on go.mod
> +	golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd // indirect
```suggestion

```

2022-03-04 15:13 UTC, giunatale requested changes

2022-03-04 15:13 UTC, giunatale commented on x/reward/types/reward_pool.go
>  	sdk "github.com/cosmos/cosmos-sdk/types"
goimports

2022-03-04 15:51 UTC, lubtd approved these changes

2022-03-04 15:51 UTC, merged