remove ids and test
tendermint/spn pull request #616
Opened 2022-03-10 16:40 UTC by aljo242

Closes #607

### What does this PR does?

- Add `ClearVerifiedClientIDs()` method
- Add `monitoringc` dependency to `launch` keeper
- Add tests

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Include tests
- [X] Respect code style and lint

2022-03-10 17:23 UTC, lubtd commented
Looks good, testing right now

2022-03-10 20:54 UTC, lubtd commented
I can create the connection with a non-verified IBC client. I don't think this is related to this PR but I need to investigate more

2022-03-11 09:35 UTC, lubtd requested changes

2022-03-11 09:35 UTC, lubtd commented on x/monitoringc/keeper/verified_client_id.go
> +func (k Keeper) ClearVerifiedClientIDs(ctx sdk.Context, launchID uint64) {
We must also remove all entries of `LaunchIDFromVerifiedClientID` for each of the client IDs in the array. This is the actual entry read when doing the handshake, hence the error I mentioned above

2022-03-15 11:04 UTC, lubtd submitted a review, later dismissed
👍

2022-03-16 12:22 UTC, giunatale requested changes

2022-03-16 12:22 UTC, giunatale commented on x/launch/keeper/msg_revert_launch.go
> +	k.monitoringcKeeper.ClearVerifiedClientIDs(ctx, msg.LaunchID)
linting says error is not checked. is it intentional?

2022-03-16 15:30 UTC, giunatale submitted a review, later dismissed

2022-03-16 15:35 UTC, lubtd commented
> @giunatale I returned an error from that function. Error conditions from ClearVerifiedClientIDs() are already tested in the monitoringc package so I did not add an extra test.

We may not have created a verified client before reverting (it will even always be the case in practice) therefore we should either only call `ClearVerifiedClientIDs ` if verified client IDs exist or filter out the not found error

(or maybe simply remove this error, the clear has no effect if no verified client IDs)

2022-03-16 16:08 UTC, aljo242 commented
I think removing the error makes the most sense as that's how the other keeper functions work.

2022-03-17 05:32 UTC, Pantani approved these changes

2022-03-17 07:46 UTC, merged