refactor(`reward`): distribute rewards to the operator address if no validator profile
tendermint/spn pull request #627
Opened 2022-03-16 17:20 UTC by lubtd

If no validator profile exists that associates the operator address to a validator address on SPN, we automatically distribute the rewards to the operator address account

2022-03-17 05:41 UTC, Pantani commented on x/profile/types/errors.go
> +	ErrDupAddress           = sdkerrors.Register(ModuleName, 8, "address is duplicated")
```suggestion
	ErrDupAddress           = sdkerrors.Register(ModuleName, 6, "address is duplicated")
	ErrCoordInactive        = sdkerrors.Register(ModuleName, 7, "inactive coordinator")
```

2022-03-17 15:49 UTC, giunatale approved these changes

2022-03-17 18:30 UTC, aljo242 requested changes

2022-03-17 18:30 UTC, aljo242 commented on x/reward/keeper/reward_distribution.go
> +		valAddr, err := signatureCount.GetOperatorAddress(config.GetBech32AccountAddrPrefix())
I think keeping this as `opAddr` makes sense

2022-03-18 11:13 UTC, giunatale approved these changes

2022-03-18 14:03 UTC, Pantani approved these changes

2022-03-18 16:54 UTC, merged