Add `CampaignSummary` and `CampaignSummaries` queries
tendermint/spn pull request #651
Opened 2022-03-24 12:42 UTC by lubtd

Used by the client. The queries allow to retrieve a campaign with some information associated with it:

If the campaign has at least one chain associated, retrieve for the most recent chain:
- launchID
- launchTriggered if the launch of the chain is triggered and requests can no longer be sent
- sourceURL
- sourceHash
- requestNb (pending requests for the time being)
- validatorNb

If a reward pool exist and therefore the chain is incentivized
- Rewards: coins to be distributed
- RewardsDistributed: is the reward pool closed

The PR dependency of `reward` module into `campaign` which is not ideal but this is the requirement we have if we want a more optimized query for the front-end

### USAGE
```
spnd q campaign show-campaign-summary <campaign-id>
spnd q campaign list-campaign-summary
```

### Example of output
```
campaignSummaries:
- campaign:
    allocatedShares: []
    campaignID: "1"
    campaignName: orbit
    coordinatorID: "1"
    dynamicShares: false
    mainnetID: "0"
    mainnetInitialized: false
    metadata: null
    totalShares: []
    totalSupply:
    - amount: "1000000"
      denom: orbit
  hasMostRecentChain: true
  incentivized: true
  mostRecentChain:
    launchID: "3"
    launchTriggered: true
    requestNb: "2"
    sourceHash: "0xbbb"
    sourceURL: orbito.com
    validatorNb: "1"
  rewards:
  - amount: "10"
    denom: uspn
  rewardsDistributed: false
- campaign:
    allocatedShares: []
    campaignID: "2"
    campaignName: orbit
    coordinatorID: "1"
    dynamicShares: false
    mainnetID: "0"
    mainnetInitialized: false
    metadata: null
    totalShares: []
    totalSupply:
    - amount: "1000000"
      denom: orbit
  hasMostRecentChain: false
  incentivized: false
  mostRecentChain:
    launchID: "0"
    launchTriggered: false
    requestNb: "0"
    sourceHash: ""
    sourceURL: ""
    validatorNb: "0"
  rewards: []
  rewardsDistributed: false
pagination:
  next_key: null
  total: "2"
```

2022-03-24 12:47 UTC, lubtd commented
@JoseRFelix 

For what we call "Share Allocation" for a chain, this is part of the rewards that you have in `rewards` field. There is no distinction on-chain between regular tokens "Incentives" and vouchers

To parse the vouchers: a voucher is a token with a denom of the following format: `v/{campaignID}/{voucherName}`
The percentage of share allocation for the chain for the specific voucher is:
`amountOfVoucherInRewards / totalNumberOfShare`
`totalNumberOfShare` is currently set to `100000` but eventually we can create a query to retrieve this value?

2022-03-24 16:21 UTC, Pantani commented on x/campaign/client/cli/query_campaign_summary.go
> +		Args:  cobra.ExactArgs(0),
```suggestion
		Args:  cobra.NoArgs,
```

2022-03-25 13:42 UTC, lubtd commented on x/campaign/keeper/grpc_campaign_summary.go
> +		return cs, fmt.Errorf("chain list not found for existing campaign %d", campaign.CampaignID)
Yes good point. Mind that in this case, this event should never occur, like a critical error but we don't need critical error for queries

2022-03-25 14:18 UTC, giunatale requested changes

2022-03-25 14:18 UTC, giunatale commented on proto/campaign/query.proto
> +    option (google.api.http).get = "/tendermint/spn/campaign/campaign_summary";
might be misleading as an endpoint (due to the one above). Would change it to `/tendermint/spn/campaign/campaigns_summary`

2022-03-25 14:18 UTC, giunatale commented on proto/campaign/query.proto
> +    option (google.api.http).get = "/tendermint/spn/campaign/campaign_summary";
```suggestion
    option (google.api.http).get = "/tendermint/spn/campaign/campaigns_summary";
```

2022-03-25 14:18 UTC, giunatale commented on x/campaign/client/cli/query_campaign_summary.go
> +		Short: "List information summarizing campaigns",
```suggestion
		Short: "List information summarizing all campaigns",
```

2022-03-25 20:17 UTC, Pantani submitted a review, later dismissed

2022-03-28 09:01 UTC, lubtd commented
UPDATE: added the rewards from previous chains in `previousRewards`

2022-03-28 13:58 UTC, giunatale approved these changes

2022-03-28 14:03 UTC, aljo242 approved these changes

2022-03-28 16:28 UTC, Pantani submitted a review, later dismissed

2022-03-28 17:21 UTC, merged