feat(`campaign`): add simulation for `msgEditCampaign`
tendermint/spn pull request #712
Opened 2022-04-12 13:52 UTC by giunatale

Closes #539

2022-04-12 14:40 UTC, aljo242 requested changes

2022-04-13 08:29 UTC, lubtd reviewed
Mmh seems like the message is not simulated during the execution of `make test-sim-ci`
```
"campaign": {
  "add_shares": {
   "failure": 3,
   "ok": 11
  },
  "add_vesting_options": {
   "failure": 9,
   "ok": 8
  },
  "burn_vouchers": {
   "failure": 1,
   "ok": 13
  },
  "create_campaign": {
   "failure": 7,
   "ok": 21
  },
  "initialize_mainnet": {
   "failure": 5
  },
  "mint_vouchers": {
   "failure": 9,
   "ok": 8
  },
  "redeem_vouchers": {
   "failure": 10,
   "ok": 14
  },
  "unredeem_vouchers": {
   "failure": 5,
   "ok": 13
  },
  "update_total_supply": {
   "failure": 10
  }
 },
```

2022-04-13 16:26 UTC, aljo242 approved these changes

2022-04-13 18:22 UTC, lubtd approved these changes

2022-04-13 18:22 UTC, merged