feat(`mint`): add `mint` module
tendermint/spn pull request #794
Opened 2022-05-13 05:05 UTC by giunatale

Closes #780 
Closes #781

### What does this PR does?

Adds a forked version of the `mint` module.
Unfortunately I could not fork the osmosis module since it depends on their epoch module, and so it was unfit.
I opted to start with the vanilla mint module as a baseline, with the dynamic inflation rate. In the future, we could explore some capping mechanism, for instance a reduction after a year worth of blocks as done in the juno [`mint`](https://github.com/CosmosContracts/juno/blob/main/x/mint/abci.go#L29) module.

The module distributes inflation to 3 parties:
- staking
- the future-to-be module account of the `incentive` modules (currently commented out in `keeper.go`)
   the idea is to send rewards directly to the `incentives` module account so that the module itself can handle the accumulated rewards independently.
- community pool

I have opted to not include at this time a "developers" rewards or "strategic reserve" rewards because this need to be thought out later. We could explore a similar design as per osmosis where a weighted list of addresses, that can be changed through governance, receive rewards from inflation. Not sure if doing this per-block is efficient though. Hence, leaving it aside.

2022-05-13 09:05 UTC, lubtd reviewed
LGTM staking rewards can be distributed

I would suggest setting params for the module in `config.yml`

2022-05-13 11:36 UTC, lubtd approved these changes

2022-05-16 12:30 UTC, aljo242 requested changes
This and a minor lint issue need to be fixed imo.  I can just push these minor changes.

2022-05-16 12:30 UTC, aljo242 commented on x/mint/module.go
> +var _ module.AppModuleBasic = AppModuleBasic{}
```suggestion
```

This is duplicate no?

2022-05-16 12:46 UTC, aljo242 approved these changes

2022-05-16 15:12 UTC, lubtd approved these changes

2022-05-16 15:12 UTC, merged