feat: Implement peer empty connection
tendermint/spn pull request #822
Opened 2022-05-30 08:07 UTC by ivanovpetr

2022-05-30 08:22 UTC, lubtd commented
I'm trying to figure out if the NodeID, `id` in `Peer`, is still necessary for empty connection or if it could be moved into `tcpAddress` and `httpTunnel`

The node always has a node ID in the P2P network even if the public address is not exposed. But potentially this information is not necessary on-chain

2022-05-30 15:09 UTC, lubtd approved these changes

2022-05-31 14:01 UTC, aljo242 requested changes

2022-06-01 16:51 UTC, Pantani approved these changes

2022-06-02 17:51 UTC, ilgooz commented
> I'm trying to figure out if the NodeID, `id` in `Peer`, is still necessary for empty connection or if it could be moved into `tcpAddress` and `httpTunnel`
> 
> The node always has a node ID in the P2P network even if the public address is not exposed. But potentially this information is not necessary on-chain

Good point, any updates on this?

In such case we don't need this PR, we can just NOT set the `peer` field in `GenesisValidator` which makes sense to me.

2022-06-02 19:11 UTC, lubtd commented
>Good point, any updates on this?
In such case we don't need this PR, we can just NOT set the peer field in GenesisValidator which makes sense to me.

We let it for now as the Node ID is a general information

2022-06-03 07:38 UTC, lubtd approved these changes

2022-06-03 07:38 UTC, merged