chore: sync `main`
tendermint/spn pull request #904
Opened 2022-07-25 09:00 UTC by lubtd

Sync `main` branch with audit fixes

2022-07-25 12:42 UTC, aljo242 requested changes
Run `make format`

2022-07-25 16:48 UTC, tbruyelle approved these changes
LGTM :+1:

2022-07-26 08:21 UTC, lubtd commented
@aljo242 any other comments?

2022-07-26 15:28 UTC, aljo242 approved these changes
LGTM !

2022-07-26 15:29 UTC, merged